[package]
name = "mailstrom"
version = "0.1.0-unstable"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dev-dependencies]
env_logger = "0.3"

[dependencies]
uuid = { version = "0.3", features = [ "v4" ] }
email-format = { git = "https://github.com/mikedilger/email-format", branch = "master" }
resolv = "0.1"
lettre = "0.6"
